<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <!-- TODO -->
    <NoWarn>CS8602;CS8603;CS8604</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\jaytwo.FluentHttp\jaytwo.FluentHttp.csproj" />
    <PackageReference Include="jaytwo.MimeHelper" Version="0.1.3" />
  </ItemGroup>

</Project>
